### ISSUE TITLE
No diff/patch created.

### ISSUE THREAD

**Issue by alfagt43** [reproteq/DiffPatchWpf#3]
When i press "diff" nothing is created. "patch.ips is created" but isn't really anywhere.
W10 x64 - NET 4.8, same result running as admin.

**Comment by reproteq** [comment]
wat filenames you use?
you see youtub video , really work.
mi tool is only a wpf interface for easy use for not write cmd in shell.
you can try with cmd line in windows shell
hdiff.exe ori.bin mod.bin diff.ips
hpatch.exe otherori.bin diff.ips otherori-patched.bin

**Comment by alfagt43** [comment]
I tryed with a lot of files, and a lot of filenames. Yes, your tool looks really great. Unfortunately, he don't make new file. I will try and report like you suggested.

**Comment by alfagt43** [comment]
Ok, it works. I figured out that i have to place the files i want to patch directly into the software folder.

**Comment by reproteq** [comment]
see new version and test
not spaces in directori names or filenames or not work
